version: '3'
services:
  app:
    image: sub_iot_sub
    build: .
    container_name: sub-iot-sub
    volumes:
      - .:/usr/src/sga_iot_sub
    working_dir: /usr/src/sga_iot_sub
    #command: sga-iot-sub run --broker labotec-broker.ddns.net --topic Cuarto/Ingresa
    command: sga-iot-sub run --broker ${BROKER_NAME} --port ${BROKER_PORT} --topic ${BROKER_TOPIC} --username ${BROKER_USERNAME} --password ${BROKER_PASSWORD}
    environment:
     - BROKER_NAME=${BROKER_NAME}
     - BROKER_PORT=${BROKER_PORT}
     - BROKER_TOPIC=${BROKER_TOPIC}
     - BROKER_USERNAME=${BROKER_USERNAME}
     - BROKER_PASSWORD=${BROKER_PASSWORD}
